
services:
  stadtbucheri-db-service:
    image: 'postgres:14-alpine'
    container_name: 'stadtbucheri-db-container'
    profiles: [ db, full ]
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=sa'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=postgres'

  stadtbucheri-springboot-app:
    image: 'stadtbucheri:0.0.1-SNAPSHOT' 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'stadtbucheri-springboot-container'
    profiles: [ service, full ]
    ports:
      - 9091:9091 
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stadtbucheri-db-service:5432/postgres
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    depends_on:
      - stadtbucheri-db-service
