spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?user=sa&password=
    driver-class-name: org.postgresql.Driver
    platform: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
